### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by jameslamb** [ntdef/groupby#1]

**Comment by ntdef** [comment]
I should probably add a README, huh

**Comment by jameslamb** [comment]
@ntdef any update on this??????? I'm totally blocked until this issue is resolved, thanks.

**Comment by ntdef** [comment]
Oh no!!!!! Sorry it took so long to get you unblocked :grimacing:. [I just made a PR](https://github.com/ntdef/groupby/pull/2) :sweat_smile: . Hopefully you can review it and confirm that it's suitable?

**Comment by jameslamb** [comment]
YES FINALLY THANK YOU 🙌
